name: Get Google Secret Manager secrets
on:
  workflow_call:
    inputs:
      # A JSON list(map) object, eg.
      # '[
      #   {
      #     "secret": "my-secret",
      #     "provider": "my-provider",
      #     "sa": "my-service-account,
      #   },
      # ]'
      secrets:
        required: true
        type: string
    outputs:
      secrets:
        description: A list of secrets extracted from Secret Manager
        value: ${{ jobs.get-gsm-secrets.outputs.secrets }}

jobs:
  get-gsm-secrets:
    name: get secret manager secrets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        secret: ${{fromJson(inputs.secrets)}}
    outputs:
      secrets: ${{ steps.get-secret.outputs.secret }}
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ matrix.provider }}
          service_account: ${{ matrix.sa }}

      - name: Get secrets from Secret Manager
        uses: google-github-actions/get-secretmanager-secrets@v0
        id: get-secret
        with:
          secrets: |-
            secret: ${{ matrix.secret }}

