name: Helm PR workflow
on:
  workflow_call:
    inputs:
      workload-identity-provider:
        required: true
        type: string
      service-account:
        required: true
        type: string
      install-gcs-plugin:
        default: true
        type: boolean
      repo-name:
        required: true
        type: string
      repo-url:
        required: true
        type: string
      chart-name:
        required: true
        type: string
jobs:
  pr-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}
      - if: ${{ inputs.install-gcs-plugin }}
        run: |
          # Install Google Cloud Storage plugin
          helm plugin install https://github.com/nouney/helm-gcs
      - run: |
          # Push Helm chart to GCS registry
          helm repo add ${{ inputs.repo-name }} ${{ inputs.repo-url }}
          helm package .
          if [[ ${{ inputs.install-gcs-plugin }} == "true" ]];
            helm gcs push ${{ inputs.chart-name }}*tgz ${{ inputs.repo-name }}
          else
            helm push ${{ inputs.chart-name }}*tgz ${{ inputs.repo-name }}
          fi

